export type AuthLink = { route: 'confirm' | 'reset-password'; code: string; flowId?: string };
export const INVALID_LINK = 'El enlace venció o no es válido. Solicitá uno nuevo desde este dispositivo.';
/** Accept only the exact callback URLs generated by this installation. Never log the URL. */
export function parseAuthLink(raw: string, callbacks: { confirm: string; recovery: string }): AuthLink | null {
  let url: URL;
  try { url = new URL(raw); } catch { return null; }
  const route = (['confirm', 'reset-password'] as const).find(route => {
    const allowed = new URL(route === 'confirm' ? callbacks.confirm : callbacks.recovery);
    return url.protocol === allowed.protocol && url.host === allowed.host && url.pathname === allowed.pathname;
  });
  if (!route) return null;
  const fragment = new URLSearchParams(url.hash.slice(1));
  if (url.searchParams.has('error') || url.searchParams.has('error_code') || fragment.has('error') || fragment.has('error_code')) throw new Error(INVALID_LINK);
  // PKCE validates the one-time code against the verifier stored on this device.
  // setSession(fragment tokens) only emits SIGNED_IN and is not a recovery gate.
  const codes = url.searchParams.getAll('code');
  if (codes.length !== 1 || !codes[0] || url.hash) throw new Error(INVALID_LINK);
  const ids = url.searchParams.getAll('sb_flow_id');
  if (ids.length > 1 || (ids.length === 1 && !ids[0])) throw new Error(INVALID_LINK);
  return { route, code: codes[0], ...(ids[0] ? { flowId: ids[0] } : {}) };
}

